name: Deploy Notification To production phcode.dev

on:
  repository_dispatch:
    types: [deploy-production]

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Event triggered by
        run: |
          echo source: ${{github.event.client_payload.source}}, workflow: ${{github.event.client_payload.workflow}}, action_run_id: ${{github.event.client_payload.run_id}}, action_run_number: ${{github.event.client_payload.run_number}}, sha: ${{ github.event.client_payload.sha }}, github_ref: ${{ github.event.client_payload.ref }}
      - name: Checking Out https://github.com/phcode-dev/phoenix
        uses: actions/checkout@v2
        with:
          repository: phcode-dev/phoenix
          path: './phoenix'
      - name: Building phoenix release artifacts
        working-directory: ./phoenix
        run: |
          npm install
          npm run release
        shell: bash
      - name: Copying release artifacts to public folder
        run: |
          mkdir -p ./public
          cp -r ./phoenix/dist/. ./public
        shell: bash
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: phcode.dev
